core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registro, name='registro'),
    path('produtos/', views.produtos, name='produtos'),
    path('pedidos/', views.pedidos, name='pedidos'),
    path('js/', views.js, name='js'),
    path('api/produtos/', views.ProdutosLista.as_view(), name='api-produtos'),
    path('api/produto/<int:produto_id>/', views.ProdutoLista.as_view(), name='api-produto'),
    path('venda/<int:venda_pk>/', views.venda, name='venda'),
]

mercado/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Cliente(models.Model):
    cliente     = models.CharField('Nome Cliente', max_length=15)
    cpf         = models.CharField('CPF', max_length=11)

    def __str__(self):
        return self.cliente


class Produto(models.Model):
    produto     = models.CharField('Nome Produto', max_length=20)
    descricao   = models.TextField('Descrição', max_length=500)
    preco       = models.DecimalField('Preço', decimal_places=2, max_digits=7, validators=[MinValueValidator(0.01)])

    def __str__(self):
        return self.produto


class Pedido(models.Model):
    cliente     = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    criado      = models.DateField('Criado em', auto_now_add=True)
    modificado  = models.DateField('Modificado em', auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.id)


class DetalhePedido(models.Model):
    pedido      = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto     = models.ForeignKey(Produto, on_delete=models.CASCADE)
    quantidade  = models.PositiveSmallIntegerField('quantidade')
    preco       = models.DecimalField('Preço', decimal_places=2, max_digits=7)

    def __str__(self):
        return str(self.pedido)

core/forms.py
from django import forms
from .models import Pedido
from .models import DetalhePedido

class PedidoForm(forms.ModelForm):

    class Meta:
        model = Pedido
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PedidoForm, self).__init__(*args, **kwargs)
        self.fields['cliente'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['cliente'].widget.attrs['id'] = 'pedido-form-id'

class DetalhePedidoForm(forms.ModelForm):

    class Meta:
        model = DetalhePedido
        fields = '__all__'


    def __init__(self, *args, **kwargs):
        super(DetalhePedidoForm, self).__init__(*args, **kwargs)
        self.fields['preco'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['preco'].widget.attrs['min'] = '0.01'
        self.fields['produto'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['quantidade'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['quantidade'].widget.attrs['min'] = '0'

core/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import resolve_url
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.forms.models import inlineformset_factory
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import Produto
from .models import Pedido
from .models import DetalhePedido
from .forms import PedidoForm
from .forms import DetalhePedidoForm
from .serializers import ProdutoSerializer



# Create your views here.
def index(request):
    return render(request, 'core/index.html')


def produtos(request):
    produtos = Produto.objects.all()
    context = {
        'produtos':produtos,
    }
    return render(request, 'core/produtos.html', context)


def venda(request, venda_pk):
    pedido = Pedido.objects.get(pk=venda_pk)
    detalhes = pedido.detalhepedido_set.all()
    context = {
        'pedido': pedido,
        'detalhes': detalhes,
    }
    return render(request, 'core/venda.html', context)

def js(request):
    produtos = Produto.objects.all()
    context = {
        'produtos':produtos,
    }
    return render(request, 'core/js.html', context)

def pedidos(request):
    produtos = Produto.objects.all()
    pedidos = Pedido.objects.all()

    pedido_forms = Pedido()
    item_pedido_formset = inlineformset_factory(
        Pedido, DetalhePedido, form=DetalhePedidoForm,extra=0, can_delete=False, min_num=1, validate_min=True
    )

    if request.method == 'POST':
        forms = PedidoForm(request.POST, request.FILES,
                           instance=pedido_forms, prefix='main')
        formset = item_pedido_formset(
            request.POST, request.FILES, instance=pedido_forms, prefix='produto'
        )
        if forms.is_valid() and formset.is_valid():
            forms = forms.save()
            formset.save()
            return HttpResponseRedirect(resolve_url('core:venda', forms.pk))

    else:
        forms = PedidoForm(instance=pedido_forms, prefix='main')
        formset = item_pedido_formset(instance=pedido_forms, prefix='produto')

    context = {
        'pedidos' : pedidos,
        'produtos': produtos,
        'forms' : forms,
        'formset' : formset,
    }
    return render(request, 'core/pedidos.html', context)


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            authenticated_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, authenticated_user)
            return redirect('core:index')
        else:
            return render(request, 'core/login.html', {'login_form':form})
    else:
        form = AuthenticationForm()
    return render(request, 'core/login.html', {'login_form':form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:index'))


def registro(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            form.save()
            return redirect('core:index')
        else:
            if form.errors:
                return render(request,'core/registro.html', context)
    else:
        form = UserCreationForm()
        context = {'form':form}
        return render(request, 'core/registro.html', context)


# Views da API
class ProdutosLista(APIView):
    def get(self, request):
        produtos = Produto  .objects.all()
        context = {'request': request}
        serializer = ProdutoSerializer(produtos, context=context, many=True)
        return Response(serializer.data)


class ProdutoLista(APIView):
    def get(self, request, produto_id):
        produto = Produto.objects.get(id=produto_id)
        context = {'request': request}
        serializer = ProdutoSerializer(produto, context=context)
        return Response(serializer.data)

core/templates/core/JS.html
{% extends 'core/base.html' %}


{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">JavaScript</h1>
      <p class="lead">Para testar formulários com Ajax.</p>
    </div>

    <div class="container">

        <div id="pai">
          
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <label class="input-group-text" for="produto">Produto</label>
            </div>
            <select class="custom-select" id="produto" onchange="prod(this)">
              <option>Selecione aqui o produto</option>
              {% for produto in produtos %}
              <option>{{ produto }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="row">            
            <div class="col-md-3">
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="quantidade">Quantidade</label>
                </div>
                <input type="number" min="0" class="form-control" id="quantidade" disabled onchange="qtd()">
              </div>
            </div>

            <div class="col-md-4">
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="preco">Preço un.</label>
                </div>
                <input type="text" class="form-control" id="preco" readonly>
              </div>
            </div>

            <div class="col-md-5">
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <label class="input-group-text" for="preco_total">Preço total</label>
                </div>
                <input type="text" class="form-control" id="preco_total" readonly>
              </div>
            </div>
          </div>
          <hr>

        </div>
        <button class="btn btn-sm btn-success" onclick="add()" id="add-botao">Adicionar Produtos</button>
    </div>

{% block scripts %}


{% endblock scripts %}
<script>  
// request and populate price input
function prod(product){
  if ($('#produto').val() == 'Selecione aqui o produto'){
    $('#quantidade').attr('disabled', true)
    $('#preco').val('')
    $('#preco_total').val('')
    $('#quantidade').val('')
  } else {
    $.ajax({
      type: 'GET',
      url: 'http://localhost:8000/api/produtos/',
      dataType: 'json',
      async: 'true',
      success: function (data) {
        for (i=0; i < data.length; i++) {
          if (data[i].produto == $('#produto').val()) {
            console.log('é igual')
            $('#preco').val(data[i].preco)
          }
        }
      }
    })
    $('#quantidade').attr('disabled', false)
  }
}

// populate total price input
function qtd () {
  var quantidade = $('#quantidade').val()
  var preco_unit = $('#preco').val()
  $('#preco_total').val((quantidade * preco_unit).toFixed(2))
}
</script>

<script>
  function add() {
    var count = $('#pai').children().length;
    var form_produto = $('#form-produto').html();
    var upd_form_produto = form_produto.replace(/__prefix__/g, count);
    $('#pai').append(upd_form_produto)
    console.log(count)
  }
</script>

<script type="text/html" id="form-produto">
  <div class="input-group mb-3">
      <div class="input-group-prepend">
        <label class="input-group-text" for="produto-__prefix__">Produto</label>
      </div>
      <select class="custom-select" id="produto-__prefix__" onchange="prod(this)">
        <option>Selecione aqui o produto</option>
        {% for produto in produtos %}
        <option>{{ produto }}</option>
        {% endfor %}
      </select>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="quantidade-item-__prefix__">Quantidade</label>
        </div>
        <input type="number" min="0" class="form-control" id="quantidade-item-__prefix__" disabled onchange="qtd()">
      </div>
    </div>

    <div class="col-md-4">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="preco-__prefix__">Preço un.</label>
        </div>
        <input type="text" class="form-control" id="preco-__prefix__" readonly>
      </div>
    </div>

    <div class="col-md-5">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text" for="preco_total-__prefix__">Preço total</label>
        </div>
        <input type="text" class="form-control" id="preco_total-__prefix__" readonly>
      </div>
    </div>

  </div>
  <hr>
</script>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    {% block css %}
    {% endblock %}


    <title>Hello, world!</title>
  </head>
  {% block body %}
  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Mercado</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="{% url 'core:index' %}">Home</a>
        <a class="p-2 text-dark" href="{% url 'core:produtos' %}">Produtos</a>
        <a class="p-2 text-dark" href="{% url 'core:pedidos' %}">Pedidos</a>
        <a class="p-2 text-dark" href="{% url 'core:js' %}">JS</a>
      </nav>
      {% if user.is_authenticated %}
      <a class="btn btn-outline-danger" href="{% url 'core:logout' %}">Logout</a>
      {% else %}
      <a class="btn btn-outline-primary" href="{% url 'core:login' %}">Login</a>
      {% endif %}
    </div>

    {% block content %}
    {% endblock %}

    <div class="container">
      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
          </div>
          <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Cool stuff</a></li>
              <li><a class="text-muted" href="#">Random feature</a></li>
              <li><a class="text-muted" href="#">Team feature</a></li>
              <li><a class="text-muted" href="#">Stuff for developers</a></li>
              <li><a class="text-muted" href="#">Another one</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Team</a></li>
              <li><a class="text-muted" href="#">Locations</a></li>
              <li><a class="text-muted" href="#">Privacy</a></li>
              <li><a class="text-muted" href="#">Terms</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    {% block script %}
    {% endblock script %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block select %}
    {% endblock select %}

    {% block scripts %}
    {% endblock scripts %}
  </body>
  {% endblock body %}
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}


{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Bem vindo ao nosso site!</h1>
      <p class="lead">Faça seu pedido e receba os produtos em casa.</p>
    </div>
{% endblock %}

core/templates/core/login.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'core/css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post">
      {% csrf_token %}
      <h1 class="display-4 mb-2">Mercado</h1>
      <h1 class="h5 mb-3 font-weight-normal">Faça o login</h1>

      <input type="text"
         class="form-control"
         name="{{ login_form.username.name }}"
         placeholder="{{ login_form.username.label }}"
         id="{{ login_form.username.id_for_label }}"
         {% if login_form.username.value != None %}value="{{ login_form.username.value|stringformat:'s' }}"{% endif %}
         maxlength="{{ login_form.username.field.max_length }}"
         {% if login_form.username.field.required %}required{% endif %}>

      <input type="password"
         class="form-control"
         name="{{ login_form.password.name }}"
         placeholder="{{ login_form.password.label }}"
         id="{{ login_form.password.id_for_label }}"
         {% if login_form.password.value != None %}value="{{ login_form.password.value|stringformat:'s' }}"{% endif %}
         maxlength="{{ login_form.password.field.max_length }}"
         {% if login_form.password.field.required %}required{% endif %}>

      <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">Sign in</button>
      <a href="{% url 'core:registro' %}" class="">Ou registre-se aqui</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

core/templates/core/pedidos.html
{% extends 'core/base.html' %}

{% block css %}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet"/>
{% endblock css %}

{% block select %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
{% endblock select %}


{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Pedidos</h1>
      <p class="lead">Faça aqui o seu pedido.</p>
    </div>

    <div class="container">
          <form action="" method="POST">
              {% csrf_token %}
              <div class="row">
                  <div class="col-xs-8 col-md-5">
                      <h3 class="lead">Cliente</h3>
                      {{ forms.cliente }}
                      {{ formset.management_form }}
                  </div>
              </div>

              <h3 class="lead mt-4">Produtos</h3>
              <div id="order" class="">
                  {% for item_order_form in formset %}
                  <div id="item-{{ forloop.counter0 }}" class="form-inline" style="">
                    {% for item in formset %}
                    <span class="">{{ item.produto }}</span>
                    <span class="">{{ item.quantidade }}</span>
                    <span class="">{{ item.preco }}</span>
                    {% endfor %}
                  </div>
                  {% endfor %}
              </div>
              <button class="btn btn-sm btn-info my-4" id="add-item">Add item</button>

              <div class="form-inline buttons">
                  <button class="btn btn-primary pull-right" value="Save">
                      <i class="fa fa-floppy-o"></i>
                      Salvar
                  </button>
              </div>
          </form>
    </div>

{% endblock %}

    {% block script %}
    <script>
		$(document).ready(function () {
			$("#add-item").click(function (ev) {
				ev.preventDefault();
				var count = $('#order').children().length;
				var tmplMarkup = $("#item-order").html();
				var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
				$("div#order").append(compiledTmpl);
				// update form count
				$('#id_produto-TOTAL_FORMS').attr('value', count + 1);
				$('#id_produto-TOTAL_FORMS').attr('class', form-control-sm);
				$('#id_produto-' + (count) + '-produto').select2();
				$('html, body').animate({
					scrollTop: $("#add-item").position().top - 200
				}, 800);
			  
        	});
			// {}
			$('select').select2();
        });
    </script>

        <script type="text/html" id="item-order">
      <div id="item-__prefix__" class="form-inline p-0" style="margin-top: 10px">
        {% for item in formset.empty_form %}
        <span class="">{{ item }}</span>
        {% endfor %}
      </div>
	</script>

    {% endblock script %}

core/templates/core/produtos.html
{% extends 'core/base.html' %}


{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Produtos</h1>
      <p class="lead">Confira aqui nossa lista de produtos.</p>
    </div>

    <div class="container">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Produto</th>
            <th>Preço</th>
            <th>Descrição</th>
          </tr>
        </thead>
        <tbody>
          {% for produto in produtos %}
          <tr>
            <td>{{ produto.produto }}</td>
            <td>R$ {{ produto.preco }}</td>
            <td>{{ produto.descricao|slice:":60" }}...</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

{% endblock %}

core/templates/core/registro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'core/css/signin.css' %}">
  </head>

  <body class="text-center">
    <form class="form-signin" method="post">
      {% csrf_token %}
      <h1 class="display-4 mb-2">Mercado</h1>
      <h1 class="h5 mb-3 font-weight-normal">Faça seu cadastro</h1>
      <input type="text" name="username" maxlength="150" autofocus required id="id_username" class="form-control mb-3" placeholder="Usuário"/>
      <input type="password" name="password1" required id="id_password1" class="form-control mt-2" placeholder="Senha" />
      <input type="password" name="password2" required id="id_password2" class="form-control" placeholder="Repita sua senha" />
      <button class="btn btn-lg btn-primary btn-block mb-3" type="submit">Cadastrar</button>
      <br>
      <p class="text-danger">
        {{ form.username.errors.as_text }}
        {{ form.password1.errors.as_text }}
        {{ form.password2.errors.as_text }}
      </p>
      <a href="{% url 'core:login' %}" class="">Se já tem cadastro, faça o login aqui</a>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>
  </body>
</html>

core/templates/core/venda.html
{% extends 'core/base.html' %}


{% block content %}

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Venda</h1>
      <p class="lead">Confira aqui o resumo do seu pedido.</p>
    </div>

    <div class="container">
      <table class="table table-hover">
        <thead>
          <tr align="center">
            <th colspan="3">
            Cliente: {{ pedido.cliente }}
            </th>
          </tr>
          <tr>
            <th>Produto</th>
            <th>Preço</th>
            <th>Descrição</th>
          </tr>
        </thead>
        <tbody>
          {% for detalhe in detalhes %}
          <tr>
            <td>{{ detalhe.produto }}</td>
            <td>R$ {{ detalhe.preco }}</td>
            <td>{{ detalhe.produto.descricao|slice:":80" }}...</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

{% endblock %}